root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
# Array of commands to run before each build.
pre_cmd = ["pnpm dlx @tailwindcss/cli -i ./tailwind.css -o ./static/styles.css"]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o wiki wiki.go" # -gcflags='all=-N -l'
# Array of commands to run after ^C.
post_cmd = []

# Binary file yields from `cmd`.
bin = "wiki"
# Customize binary, can setup environment variables when run your app.
full_bin = ""
# Add additional arguments when running binary (bin/full_bin). Will run './tmp/main hello world'.
args_bin = []

# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "templ", "html"]
# Ignore these filename extensions or directories.
exclude_dir = ["assets", "tmp", "vendor", "testdata", "node_modules", "static"]
# Watch these directories if you specified.
include_dir = ["tmpl"]
# Exclude files.
exclude_file = []
# Watch these files.
include_file = ["tailwind.css"]
# Exclude specific regular expressions.
exclude_regex = ["_test.go"]
# Exclude unchanged files.
exclude_unchanged = false
# Follow symlink for directories
follow_symlink = true

# This log file is placed in your tmp_dir.
log = "build-errors.log"

# Poll files for changes instead of using fsnotify.
poll = false
# Poll interval (defaults to the minimum interval of 500ms).
poll_interval = 500 # ms

# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms
# Delay after sending Interrupt signal
kill_delay = "0s" # s
# Rerun binary or not
rerun = false
# Delay after each execution
rerun_delay = 500 # ms
# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = false
# Stop running old binary when build errors occur.
stop_on_error = true

[color]
# Customize each part's color. If no color found, use the raw app log.
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
# Only show main log (silences watcher, build, runner)
main_only = false
# silence all logs produced by air
silent = false
# Show log time
time = true

[misc]
# Delete tmp directory on exit
clean_on_exit = false

[proxy]
# Enable live-reloading on the browser.
enabled = true
app_port = 8080
proxy_port = 9000

[screen]
clear_on_rebuild = true
keep_scroll = false
