root = "."
tmp_dir = "storage/temp"

[build]
  cmd = "go build -o ./storage/temp/main ."

  bin = "./storage/temp/main"
  full_bin = ""

  include_ext = ["go", "tpl", "tmpl", "templ", "html"]
  exclude_dir = ["storage", "database"]
  include_dir = []
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false

  log = "build-errors.log"

  delay = 1000
  kill_delay = "0s"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
